[build]
  command = "npm run build"
  publish = "dist/browser"

 [[redirects]]
  from = "/api/*"
  to   = "https://smart-shopping-list-api.onrender.com/:splat"
  status = 200
  force = true

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200

